In [10]:
import pandas as pd

In [11]:
monstri = pd.read_csv('monstri.csv', index_col = 'Ime')

In [12]:
pd.options.display.max_rows = 14

In [13]:
monstri

,Atribut,Level_Rank,Tip,ATK,DEF
Ime,,,,,
Armityle the Chaos Phantom,DARK,12,Fiend,0,0
Assault Blackwing - Onimaru the Divine Thunder,DARK,12,Winged Beast,3000,2000
"Barbaroid, the Ultimate Battle Machine",EARTH,12,Machine,4000,4000
Blue-Eyes Ultimate Dragon,LIGHT,12,Dragon,4500,3800
Cosmic Blazar Dragon,WIND,12,Dragon,4000,4000
Dragon Master Knight,LIGHT,12,Dragon,5000,5000
Dystopia the Despondent,DARK,12,Fiend,5000,5000
...,...,...,...,...,...
Unknown Synchron,DARK,1,Machine,0,0
Vijam the Cubic Seed,DARK,1,Fiend,0,0
Volcanic Rat,FIRE,1,Pyro,500,500
Volcanic Shell,FIRE,1,Pyro,100,0
Vylon Sphere,LIGHT,1,Machine,400,400
Watapon,LIGHT,1,Fairy,200,300
Watch Dog,FIRE,1,Pyro,0,0